# RFM Calculation

## Importing Required Libraries And Scripts

In [2]:
import pandas as pd
import datetime as dt
import os
import sys

# --- Path ---
# Adding project root to sys.path
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)

# --- Importing Custom Scripts ---
from scripts import utils

# loading processed_data.csv
try:
    df_clean = pd.read_csv('../data/processed_data.csv', encoding='utf-8')
    # Convert the date column back to datetime format
    df_clean['InvoiceDate'] = pd.to_datetime(df_clean['InvoiceDate'])
    print("Cleaned data loaded successfully.")
except FileNotFoundError:
    print("processed_data.csv not found. Please clean and save the data in the previous notebook.")

Cleaned data loaded successfully.

## Proprocessing for RFM

In [ ]:
# Calculating TotalPrice field
df_processed = utils.preprocess_data(df_clean.copy())
display(df_processed.head())

Calculated TotalPrice column.

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,537359,22469,HEART OF WICKER SMALL,22,2024-01-26 13:12:00,11.32,12813,Netherlands,249.04
1,538693,71053,WHITE METAL LANTERN,46,2024-12-06 23:36:00,19.71,14324,United Kingdom,906.66
2,537160,22086,PAPER CHAIN KIT 50'S CHRISTMAS,4,2024-04-26 05:36:00,4.64,16563,United Kingdom,18.56
3,538035,22960,JAM MAKING SET WITH JARS,1,2024-02-20 03:50:00,16.74,16806,Switzerland,16.74
4,536671,21931,JUMBO STORAGE BAG SUKI,45,2024-05-28 10:54:00,4.47,15363,United Kingdom,201.15

## Calculating RFM Metrics

In [5]:
rfm_df = utils.calculate_rfm(df_processed)
print("RFM Metrics:")
display(rfm_df.head())

Snapshot date for Recency calculation: 2024-12-31
RFM values calculated successfully.
RFM Metrics:

            Recency  Frequency  MonetaryValue
CustomerID
12347           156          1         401.70
12348           194          3        3036.04
12349           231          1         695.57
12350           222          1         269.74
12354           325          1        2555.94

## RFM Points (Scoring)

In [6]:
rfm_scored = utils.assign_rfm_scores(rfm_df.copy())
print("RFM Scores:")
display(rfm_scored.head())

RFM scores assigned.
RFM Scores:

            Recency  Frequency  MonetaryValue R_Score F_Score M_Score
CustomerID
12347           156          1         401.70       3       1       2
12348           194          3        3036.04       3       5       5
12349           231          1         695.57       2       1       2
12350           222          1         269.74       2       1       1
12354           325          1        2555.94       1       1       5